import '../src/api'
import '../src/icons'
import 'view-design/dist/styles/iview.css'
import '../src/scss/reset.scss'
import '../src/scss/index.scss'
import '../src/scss/animate.min.scss'
import '../src/scss/font.css'
